import {
  ShieldAlert,
  Mic,
  Scale,
  Database,
  Ban,
  Server,
  ShoppingBasket,
  UserCheck,
  AlertTriangle,
} from "lucide-react";
import { LegalPage } from "./LegalPage";

const EFFECTIVE = new Date().toISOString().slice(0, 10);

export function TermsPage() {
  return (
    <LegalPage
      pageTitle="Terms & Conditions"
      description="The rules and limits that govern your use of AgriSeva-AI \u2014 including AI advisory, market data, voice, and demo workflows."
      effectiveDate={EFFECTIVE}
      contactEmail="legal@agriseva.ai"
      contactJurisdiction="These terms are governed by the laws of the Republic of India. Disputes are subject to the jurisdiction of courts in Bengaluru, Karnataka."
      intro={
        <>
          <p>
            These Terms &amp; Conditions (&ldquo;Terms&rdquo;) govern your use of
            the AgriSeva-AI platform. By creating an account or using the
            service you agree to these Terms. If you do not agree, do not use
            AgriSeva-AI.
          </p>
          <p>
            AgriSeva-AI is provided by Annam.ai (&ldquo;AgriSeva&rdquo;, &ldquo;we&rdquo;).
            We may update these Terms from time to time; continued use
            constitutes acceptance of the updated version.
          </p>
        </>
      }
      sections={[
        {
          heading: "1. Use of the platform",
          icon: <UserCheck size={18} />,
          paragraphs: [
            "You must be 18 or older and a farmer, agricultural professional, or authorized representative to use AgriSeva-AI. You agree to provide accurate information when creating an account and to keep your credentials secure.",
            "You are responsible for activity on your account. Notify us immediately at security@agriseva.ai if you suspect unauthorized access.",
          ],
        },
        {
          heading: "2. AI advisory and information limitations",
          icon: <AlertTriangle size={18} />,
          paragraphs: [
            "Answers generated by the AgriSeva-AI assistant are advisory. They are produced by large language models combined with retrieval over government data sources (Agmarknet, IMD, Soil Health Card, myscheme.gov.in).",
            "Agricultural conditions, pest pressure, market prices, and scheme eligibility change rapidly. Always independently verify recommendations and prices with your local agricultural officer, KVK, or mandi before acting on them.",
            "We do not guarantee the accuracy, completeness, or fitness for any particular purpose of AI-generated answers.",
          ],
        },
        {
          heading: "3. Market data and price information",
          icon: <Database size={18} />,
          paragraphs: [
            "Market prices displayed in the Farmer Dashboard are sourced from Agmarknet and eNAM through the AgriSeva market-intelligence service. Prices are indicative and may lag real-time mandi trades by minutes to hours.",
            "AgriSeva-AI is not a broker, aggregator, or counterparty in any commodity transaction. We do not intermediate the sale of produce.",
          ],
        },
        {
          heading: "4. Voice and calling features",
          icon: <Mic size={18} />,
          paragraphs: [
            "The AgriSeva-AI voice helpline is powered by Plivo telephony and Sarvam AI for speech recognition. Calls may be transcribed and stored for quality review; see our Privacy Policy for retention details.",
            "Misuse of the voice line \u2014 including but not limited to threats, harassment, or fraudulent impersonation \u2014 will result in immediate suspension.",
          ],
        },
        {
          heading: "5. Demo and prototype features",
          icon: <ShoppingBasket size={18} />,
          paragraphs: [
            "The buyers, lots, offers, logistics, storage, payments, and grievance screens are part of an in-development workflow prototype. Data shown there is illustrative demo data unless explicitly labelled as live. Real KYC, payment gateway, logistics provider, and warehouse integrations are planned but not yet operational.",
            "Do not use these screens to enter real personal, financial, or commercial information that you would not be comfortable discarding.",
          ],
        },
        {
          heading: "6. User-generated content",
          icon: <UserCheck size={18} />,
          paragraphs: [
            "You retain ownership of questions, photos, and other content you submit. You grant AgriSeva-AI a worldwide, royalty-free, non-exclusive licence to use, reproduce, and display that content as needed to operate and improve the service.",
            "Do not upload content that is unlawful, infringing, defamatory, or that contains personal data of other people without their consent.",
          ],
        },
        {
          heading: "7. Prohibited usage",
          icon: <Ban size={18} />,
          paragraphs: [
            "You agree not to: (a) reverse-engineer or attempt to extract source code from the platform; (b) interfere with security features; (c) scrape or bulk-download market data outside documented APIs; (d) impersonate AgriSeva-AI staff or other users; (e) use the service to send unsolicited communications.",
            "We may suspend or terminate accounts that violate these rules.",
          ],
        },
        {
          heading: "8. Third-party services",
          icon: <Server size={18} />,
          paragraphs: [
            "AgriSeva-AI integrates with Firebase, MongoDB Atlas, Google Cloud, Sarvam AI, and Plivo. Your use of those services is also subject to their respective terms.",
          ],
        },
        {
          heading: "9. Limitation of liability",
          icon: <Scale size={18} />,
          paragraphs: [
            "To the maximum extent permitted by law, AgriSeva-AI and its licensors shall not be liable for any indirect, incidental, special, or consequential damages, including loss of profits, crops, or business opportunity, arising from your use of the service.",
            "Our total aggregate liability for any claim relating to the service shall not exceed INR 1,000 or the amount you paid us in the preceding 12 months, whichever is greater.",
          ],
        },
        {
          heading: "10. Account termination",
          icon: <ShieldAlert size={18} />,
          paragraphs: [
            "You may delete your account at any time from your profile settings. We may suspend or terminate accounts that breach these Terms or that remain inactive for more than 24 months.",
          ],
        },
        {
          heading: "11. Governing law",
          icon: <Scale size={18} />,
          paragraphs: [
            "These Terms are governed by the laws of India. Any dispute shall be subject to the exclusive jurisdiction of courts in Bengaluru, Karnataka.",
          ],
        },
      ]}
    />
  );
}

export default TermsPage;