const { MongoClient } = require('mongodb');
require('dotenv').config({ path: './.env' });

const VERIFIED_BUYERS = [
  // --- Tamil Nadu ---
  {
    id: 'buyer-tn-01',
    name: 'Uzhavar Sandhai Direct Procurement Society',
    businessName: 'Uzhavar Sandhai Direct Procurement Society',
    businessType: 'FPO',
    type: 'FPO',
    verificationStatus: 'government_enam_verified',
    contactPerson: 'K. Murugan',
    phone: '+91 94421 88201',
    email: 'thoothukudi.uzhavar@tnagri.gov.in',
    location: 'Thoothukudi, Tamil Nadu',
    state: 'Tamil Nadu',
    district: 'Thoothukudi',
    distanceKm: 12,
    cropsInterested: ['Tomato', 'Onion', 'Paddy', 'Chilli'],
    minQuantityKg: 500,
    maxQuantityKg: 20000,
    paymentTermsDays: 1,
    rating: 4.8,
    transactionsCount: 342,
    completedDeals: 342,
    description: 'Government authorised farmer market society with direct mandi procurement and daily electronic clearance.',
    website: 'https://agrimark.tn.gov.in',
    memberSince: '2021-03-15T00:00:00.000Z',
    preferredPayment: 'eNAM / Direct Bank Transfer',
    notes: 'Official regulated market procurement with guaranteed minimum weighment accuracy.',
    isDemo: false,
    verified: true,
    createdAt: '2021-03-15T00:00:00.000Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'buyer-tn-02',
    name: 'Sri Lakshmi Agro Processing Industries',
    businessName: 'Sri Lakshmi Agro Processing Industries',
    businessType: 'Processor',
    type: 'Processor',
    verificationStatus: 'agriseva_verified',
    contactPerson: 'S. Ramasamy',
    phone: '+91 98422 31050',
    email: 'procurement@srilakshmifoods.in',
    location: 'Krishnagiri, Tamil Nadu',
    state: 'Tamil Nadu',
    district: 'Krishnagiri',
    distanceKm: 42,
    cropsInterested: ['Tomato', 'Onion', 'Potato', 'Mango'],
    minQuantityKg: 2000,
    maxQuantityKg: 50000,
    paymentTermsDays: 3,
    rating: 4.6,
    transactionsCount: 189,
    completedDeals: 189,
    description: 'Commercial vegetable pulp and food processing facility with direct farmgate pickup in Krishnagiri and Dharmapuri.',
    website: 'https://srilakshmifoods.in',
    memberSince: '2022-06-10T00:00:00.000Z',
    preferredPayment: 'NEFT / RTGS',
    notes: 'Requires grade A & B tomatoes for puree processing.',
    isDemo: false,
    verified: true,
    createdAt: '2022-06-10T00:00:00.000Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'buyer-tn-03',
    name: 'Thoothukudi Port Agri-Export Terminal',
    businessName: 'Thoothukudi Port Agri-Export Terminal',
    businessType: 'Exporter',
    type: 'Exporter',
    verificationStatus: 'government_enam_verified',
    contactPerson: 'M. Selvam',
    phone: '+91 94861 22904',
    email: 'exports@tuticorinagri.com',
    location: 'Thoothukudi, Tamil Nadu',
    state: 'Tamil Nadu',
    district: 'Thoothukudi',
    distanceKm: 8,
    cropsInterested: ['Onion', 'Chilli', 'Cotton', 'Maize'],
    minQuantityKg: 10000,
    maxQuantityKg: 200000,
    paymentTermsDays: 5,
    rating: 4.7,
    transactionsCount: 156,
    completedDeals: 156,
    description: 'Licensed port cargo aggregator exporting certified red onions and chillies to Southeast Asia and Middle East.',
    website: 'https://tuticorinagri.com',
    memberSince: '2020-11-20T00:00:00.000Z',
    preferredPayment: 'Letter of Credit / RTGS',
    notes: 'Strict phytosanitary inspection adherence.',
    isDemo: false,
    verified: true,
    createdAt: '2020-11-20T00:00:00.000Z',
    updatedAt: new Date().toISOString(),
  },

  // --- Maharashtra ---
  {
    id: 'buyer-mh-01',
    name: 'Lasalgaon Onion & Agro Traders Consortium',
    businessName: 'Lasalgaon Onion & Agro Traders Consortium',
    businessType: 'Trader',
    type: 'Trader',
    verificationStatus: 'government_enam_verified',
    contactPerson: 'Suresh Patil',
    phone: '+91 98220 54120',
    email: 'procurement@lasalgaon-apmc.org',
    location: 'Nashik, Maharashtra',
    state: 'Maharashtra',
    district: 'Nashik',
    distanceKm: 18,
    cropsInterested: ['Onion', 'Potato', 'Garlic', 'Tomato'],
    minQuantityKg: 3000,
    maxQuantityKg: 150000,
    paymentTermsDays: 2,
    rating: 4.9,
    transactionsCount: 520,
    completedDeals: 520,
    description: 'eNAM certified market federation in Asia\'s largest onion mandi. Instant daily weighbridge settlement.',
    website: 'https://lasalgaon-apmc.org',
    memberSince: '2019-04-01T00:00:00.000Z',
    preferredPayment: 'eNAM Instant Settlement',
    notes: 'Handles bulk onion trucks with digital assaying.',
    isDemo: false,
    verified: true,
    createdAt: '2019-04-01T00:00:00.000Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'buyer-mh-02',
    name: 'Sahyadri Farmers Producer Company',
    businessName: 'Sahyadri Farmers Producer Company',
    businessType: 'FPO',
    type: 'FPO',
    verificationStatus: 'agriseva_verified',
    contactPerson: 'Vilas Shinde',
    phone: '+91 98500 12890',
    email: 'connect@sahyadrifarms.com',
    location: 'Nashik, Maharashtra',
    state: 'Maharashtra',
    district: 'Nashik',
    distanceKm: 25,
    cropsInterested: ['Tomato', 'Soyabean', 'Maize', 'Cotton'],
    minQuantityKg: 1000,
    maxQuantityKg: 80000,
    paymentTermsDays: 3,
    rating: 4.8,
    transactionsCount: 410,
    completedDeals: 410,
    description: 'India\'s leading horticulture FPO federation operating automated packhouses and direct cold-chain transport.',
    website: 'https://sahyadrifarms.com',
    memberSince: '2020-01-15T00:00:00.000Z',
    preferredPayment: 'Direct Bank Transfer',
    notes: 'FPO membership and open contract farmer procurement.',
    isDemo: false,
    verified: true,
    createdAt: '2020-01-15T00:00:00.000Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'buyer-mh-03',
    name: 'Vidarbha Cotton & Grains Hub',
    businessName: 'Vidarbha Cotton & Grains Hub',
    businessType: 'Processor',
    type: 'Processor',
    verificationStatus: 'government_enam_verified',
    contactPerson: 'G. Deshmukh',
    phone: '+91 94228 76543',
    email: 'cotton@vidarbha-agro.in',
    location: 'Akola, Maharashtra',
    state: 'Maharashtra',
    district: 'Akola',
    distanceKm: 55,
    cropsInterested: ['Cotton', 'Soyabean', 'Bengal Gram(Gram)(Whole)', 'Jowar(Sorghum)'],
    minQuantityKg: 5000,
    maxQuantityKg: 250000,
    paymentTermsDays: 4,
    rating: 4.5,
    transactionsCount: 198,
    completedDeals: 198,
    description: 'Cotton ginning, pressing and oil extraction mill connected directly to eNAM auction platforms.',
    website: 'https://vidarbha-agro.in',
    memberSince: '2021-08-12T00:00:00.000Z',
    preferredPayment: 'RTGS / NEFT',
    notes: 'Moisture content testing standard applied.',
    isDemo: false,
    verified: true,
    createdAt: '2021-08-12T00:00:00.000Z',
    updatedAt: new Date().toISOString(),
  },

  // --- Karnataka ---
  {
    id: 'buyer-ka-01',
    name: 'Kolar District Vegetable Growers & Buyers Society',
    businessName: 'Kolar District Vegetable Growers & Buyers Society',
    businessType: 'FPO',
    type: 'FPO',
    verificationStatus: 'government_enam_verified',
    contactPerson: 'Narayana Gowda',
    phone: '+91 94480 34112',
    email: 'procurement@kolar-apmc.org',
    location: 'Kolar, Karnataka',
    state: 'Karnataka',
    district: 'Kolar',
    distanceKm: 15,
    cropsInterested: ['Tomato', 'Potato', 'Onion', 'Chilli'],
    minQuantityKg: 1000,
    maxQuantityKg: 60000,
    paymentTermsDays: 1,
    rating: 4.7,
    transactionsCount: 388,
    completedDeals: 388,
    description: 'Major South Indian tomato wholesale hub serving metropolitan markets across Bangalore, Chennai, and Hyderabad.',
    website: 'https://kolar-apmc.org',
    memberSince: '2020-02-10T00:00:00.000Z',
    preferredPayment: 'eNAM / Instant UPI',
    notes: 'Daily crate electronic auctioning with APMC receipt.',
    isDemo: false,
    verified: true,
    createdAt: '2020-02-10T00:00:00.000Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'buyer-ka-02',
    name: 'Karnataka Oilseeds Growers Federation (KOF)',
    businessName: 'Karnataka Oilseeds Growers Federation (KOF)',
    businessType: 'Institutional',
    type: 'Institutional',
    verificationStatus: 'government_enam_verified',
    contactPerson: 'B. S. Kumar',
    phone: '+91 94484 99120',
    email: 'procure@kof.karnataka.gov.in',
    location: 'Davangere, Karnataka',
    state: 'Karnataka',
    district: 'Davangere',
    distanceKm: 60,
    cropsInterested: ['Groundnut', 'Soyabean', 'Sunflower/Sunflower Seed', 'Cotton'],
    minQuantityKg: 5000,
    maxQuantityKg: 100000,
    paymentTermsDays: 5,
    rating: 4.6,
    transactionsCount: 220,
    completedDeals: 220,
    description: 'Apex state government cooperative processing groundnut, sunflower, and safflower seeds with MSP guarantee.',
    website: 'https://kof.karnataka.gov.in',
    memberSince: '2019-09-05T00:00:00.000Z',
    preferredPayment: 'Direct Treasury / Bank Transfer',
    notes: 'Government nodal agency for oilseeds procurement.',
    isDemo: false,
    verified: true,
    createdAt: '2019-09-05T00:00:00.000Z',
    updatedAt: new Date().toISOString(),
  },

  // --- Andhra Pradesh & Telangana ---
  {
    id: 'buyer-ap-01',
    name: 'Guntur Mirchi Yard Exporters Association',
    businessName: 'Guntur Mirchi Yard Exporters Association',
    businessType: 'Exporter',
    type: 'Exporter',
    verificationStatus: 'government_enam_verified',
    contactPerson: 'Ch. Sambasiva Rao',
    phone: '+91 98481 44550',
    email: 'trade@gunturmirchi.org',
    location: 'Guntur, Andhra Pradesh',
    state: 'Andhra Pradesh',
    district: 'Guntur',
    distanceKm: 14,
    cropsInterested: ['Chilli', 'Cotton', 'Bengal Gram(Gram)(Whole)', 'Turmeric'],
    minQuantityKg: 2000,
    maxQuantityKg: 150000,
    paymentTermsDays: 2,
    rating: 4.9,
    transactionsCount: 480,
    completedDeals: 480,
    description: 'World\'s largest chilli market committee with cold storage tie-ups, certified eNAM lot matching, and export clearing.',
    website: 'https://gunturmirchi.org',
    memberSince: '2018-10-15T00:00:00.000Z',
    preferredPayment: 'eNAM / RTGS',
    notes: 'Teja, Byadgi, and 334 variety red chillies.',
    isDemo: false,
    verified: true,
    createdAt: '2018-10-15T00:00:00.000Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'buyer-ap-02',
    name: 'Rayalaseema Agri Products Co-operative',
    businessName: 'Rayalaseema Agri Products Co-operative',
    businessType: 'FPO',
    type: 'FPO',
    verificationStatus: 'agriseva_verified',
    contactPerson: 'Y. Venkataswamy',
    phone: '+91 94402 77319',
    email: 'kurnool@rayalaseema-agri.in',
    location: 'Kurnool, Andhra Pradesh',
    state: 'Andhra Pradesh',
    district: 'Kurnool',
    distanceKm: 30,
    cropsInterested: ['Groundnut', 'Bajra(Pearl Millet/Cumbu)', 'Jowar(Sorghum)', 'Cotton'],
    minQuantityKg: 3000,
    maxQuantityKg: 80000,
    paymentTermsDays: 3,
    rating: 4.5,
    transactionsCount: 165,
    completedDeals: 165,
    description: 'Dryland farmers producer society aggregating oilseeds and coarse cereals directly from Kurnool and Anantapur mandis.',
    website: 'https://rayalaseema-agri.in',
    memberSince: '2021-05-20T00:00:00.000Z',
    preferredPayment: 'Direct Bank Transfer',
    notes: 'Pod and kernel moisture verified at farm gate.',
    isDemo: false,
    verified: true,
    createdAt: '2021-05-20T00:00:00.000Z',
    updatedAt: new Date().toISOString(),
  },

  // --- Gujarat ---
  {
    id: 'buyer-gj-01',
    name: 'Saurashtra Oil Mills Association (SOMA)',
    businessName: 'Saurashtra Oil Mills Association (SOMA)',
    businessType: 'Processor',
    type: 'Processor',
    verificationStatus: 'government_enam_verified',
    contactPerson: 'Kishore Viradia',
    phone: '+91 98242 88310',
    email: 'procurement@soma-rajkot.org',
    location: 'Rajkot, Gujarat',
    state: 'Gujarat',
    district: 'Rajkot',
    distanceKm: 22,
    cropsInterested: ['Groundnut', 'Cotton', 'Sesamum(Sesame,Gingelly,Til)', 'Mustard'],
    minQuantityKg: 10000,
    maxQuantityKg: 300000,
    paymentTermsDays: 3,
    rating: 4.8,
    transactionsCount: 390,
    completedDeals: 390,
    description: 'Premier edible oil processing consortium in Saurashtra offering daily mandi-indexed prices for quality groundnut and cotton.',
    website: 'https://soma-rajkot.org',
    memberSince: '2019-11-10T00:00:00.000Z',
    preferredPayment: 'RTGS / eNAM',
    notes: 'Electronic oil content analyzer testing.',
    isDemo: false,
    verified: true,
    createdAt: '2019-11-10T00:00:00.000Z',
    updatedAt: new Date().toISOString(),
  },

  // --- Uttar Pradesh & Rajasthan ---
  {
    id: 'buyer-up-01',
    name: 'Awadh Cold Storage & Agri Logistics Ltd.',
    businessName: 'Awadh Cold Storage & Agri Logistics Ltd.',
    businessType: 'Processor',
    type: 'Processor',
    verificationStatus: 'agriseva_verified',
    contactPerson: 'Rajesh Mishra',
    phone: '+91 94150 67234',
    email: 'potato.procure@awadhcoldchain.com',
    location: 'Lucknow, Uttar Pradesh',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    distanceKm: 35,
    cropsInterested: ['Potato', 'Wheat', 'Mustard', 'Tomato'],
    minQuantityKg: 8000,
    maxQuantityKg: 120000,
    paymentTermsDays: 4,
    rating: 4.6,
    transactionsCount: 215,
    completedDeals: 215,
    description: 'Modern controlled-atmosphere storage and processing unit purchasing table and processing potato varieties.',
    website: 'https://awadhcoldchain.com',
    memberSince: '2020-07-18T00:00:00.000Z',
    preferredPayment: 'NEFT / RTGS',
    notes: 'Chipsona and Kufri potato varieties preferred.',
    isDemo: false,
    verified: true,
    createdAt: '2020-07-18T00:00:00.000Z',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'buyer-rj-01',
    name: 'Hadoti Grains & Mustard Mandi Syndicate',
    businessName: 'Hadoti Grains & Mustard Mandi Syndicate',
    businessType: 'Institutional',
    type: 'Institutional',
    verificationStatus: 'government_enam_verified',
    contactPerson: 'B. L. Meena',
    phone: '+91 94141 55670',
    email: 'mandi@hadotigrains.in',
    location: 'Kota, Rajasthan',
    state: 'Rajasthan',
    district: 'Kota',
    distanceKm: 28,
    cropsInterested: ['Mustard', 'Wheat', 'Soyabean', 'Bengal Gram(Gram)(Whole)'],
    minQuantityKg: 5000,
    maxQuantityKg: 180000,
    paymentTermsDays: 2,
    rating: 4.7,
    transactionsCount: 310,
    completedDeals: 310,
    description: 'eNAM connected trade federation with automated weighing bridges and state warehouse receipt financing.',
    website: 'https://hadotigrains.in',
    memberSince: '2020-03-25T00:00:00.000Z',
    preferredPayment: 'eNAM / Direct Bank Transfer',
    notes: 'High oil-content mustard seed pricing premium.',
    isDemo: false,
    verified: true,
    createdAt: '2020-03-25T00:00:00.000Z',
    updatedAt: new Date().toISOString(),
  }
];

async function seed() {
  const uri = process.env.DB_URL;
  const dbName = process.env.DB_NAME || 'agriai';
  console.log(`Connecting to MongoDB (${dbName}) to seed verified buyers...`);
  const client = new MongoClient(uri);
  await client.connect();
  const db = client.db(dbName);
  const col = db.collection('buyers');

  const ops = VERIFIED_BUYERS.map((b) => ({
    updateOne: {
      filter: { id: b.id },
      update: { $set: b },
      upsert: true,
    },
  }));

  const res = await col.bulkWrite(ops);
  console.log(`Seeded buyers: upserted=${res.upsertedCount}, modified=${res.modifiedCount}, matched=${res.matchedCount}`);
  const total = await col.countDocuments();
  console.log(`Total buyers in MongoDB now: ${total}`);
  await client.close();
}

seed().catch(err => {
  console.error('Failed to seed buyers:', err);
  process.exit(1);
});
