/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappHistoryRouteImport } from './routes/whatsapp-history'
import { Route as FarmerRouteImport } from './routes/farmer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as PaeExpertIndexRouteImport } from './routes/pae-expert/index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as FlagsReportedIndexRouteImport } from './routes/flags-reported/index'
import { Route as FarmerIndexRouteImport } from './routes/farmer.index'
import { Route as CoordinatorIndexRouteImport } from './routes/coordinator/index'
import { Route as ChatbotIndexRouteImport } from './routes/chatbot/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as UserUserIdRouteImport } from './routes/user/$userId'
import { Route as UserHistoryUserIdRouteImport } from './routes/user-history/$userId'
import { Route as FarmerStorageRouteImport } from './routes/farmer.storage'
import { Route as FarmerProfileRouteImport } from './routes/farmer.profile'
import { Route as FarmerPricesRouteImport } from './routes/farmer.prices'
import { Route as FarmerPaymentsRouteImport } from './routes/farmer.payments'
import { Route as FarmerOffersRouteImport } from './routes/farmer.offers'
import { Route as FarmerLotsRouteImport } from './routes/farmer.lots'
import { Route as FarmerLogisticsRouteImport } from './routes/farmer.logistics'
import { Route as FarmerGrievancesRouteImport } from './routes/farmer.grievances'
import { Route as FarmerBuyersRouteImport } from './routes/farmer.buyers'
import { Route as CoordinatorProfileRouteImport } from './routes/coordinator/profile'
import { Route as FarmerLotsNewRouteImport } from './routes/farmer.lots.new'
import { Route as FarmerLotsLotIdRouteImport } from './routes/farmer.lots.$lotId'
import { Route as FarmerBuyersBuyerIdRouteImport } from './routes/farmer.buyers.$buyerId'

const WhatsappHistoryRoute = WhatsappHistoryRouteImport.update({
  id: '/whatsapp-history',
  path: '/whatsapp-history',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/farmer',
  path: '/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaeExpertIndexRoute = PaeExpertIndexRouteImport.update({
  id: '/pae-expert/',
  path: '/pae-expert/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsReportedIndexRoute = FlagsReportedIndexRouteImport.update({
  id: '/flags-reported/',
  path: '/flags-reported/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerIndexRoute = FarmerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FarmerRoute,
} as any)
const CoordinatorIndexRoute = CoordinatorIndexRouteImport.update({
  id: '/coordinator/',
  path: '/coordinator/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotIndexRoute = ChatbotIndexRouteImport.update({
  id: '/chatbot/',
  path: '/chatbot/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserUserIdRoute = UserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserHistoryUserIdRoute = UserHistoryUserIdRouteImport.update({
  id: '/user-history/$userId',
  path: '/user-history/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerStorageRoute = FarmerStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerProfileRoute = FarmerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerPricesRoute = FarmerPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerPaymentsRoute = FarmerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerOffersRoute = FarmerOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerLotsRoute = FarmerLotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerLogisticsRoute = FarmerLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerGrievancesRoute = FarmerGrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => FarmerRoute,
} as any)
const FarmerBuyersRoute = FarmerBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => FarmerRoute,
} as any)
const CoordinatorProfileRoute = CoordinatorProfileRouteImport.update({
  id: '/coordinator/profile',
  path: '/coordinator/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerLotsNewRoute = FarmerLotsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FarmerLotsRoute,
} as any)
const FarmerLotsLotIdRoute = FarmerLotsLotIdRouteImport.update({
  id: '/$lotId',
  path: '/$lotId',
  getParentRoute: () => FarmerLotsRoute,
} as any)
const FarmerBuyersBuyerIdRoute = FarmerBuyersBuyerIdRouteImport.update({
  id: '/$buyerId',
  path: '/$buyerId',
  getParentRoute: () => FarmerBuyersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/whatsapp-history': typeof WhatsappHistoryRoute
  '/coordinator/profile': typeof CoordinatorProfileRoute
  '/farmer/buyers': typeof FarmerBuyersRouteWithChildren
  '/farmer/grievances': typeof FarmerGrievancesRoute
  '/farmer/logistics': typeof FarmerLogisticsRoute
  '/farmer/lots': typeof FarmerLotsRouteWithChildren
  '/farmer/offers': typeof FarmerOffersRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/prices': typeof FarmerPricesRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/storage': typeof FarmerStorageRoute
  '/user-history/$userId': typeof UserHistoryUserIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/audit': typeof AuditIndexRoute
  '/auth': typeof AuthIndexRoute
  '/chatbot': typeof ChatbotIndexRoute
  '/coordinator': typeof CoordinatorIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/flags-reported': typeof FlagsReportedIndexRoute
  '/history': typeof HistoryIndexRoute
  '/home': typeof HomeIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/pae-expert': typeof PaeExpertIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/farmer/buyers/$buyerId': typeof FarmerBuyersBuyerIdRoute
  '/farmer/lots/$lotId': typeof FarmerLotsLotIdRoute
  '/farmer/lots/new': typeof FarmerLotsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/whatsapp-history': typeof WhatsappHistoryRoute
  '/coordinator/profile': typeof CoordinatorProfileRoute
  '/farmer/buyers': typeof FarmerBuyersRouteWithChildren
  '/farmer/grievances': typeof FarmerGrievancesRoute
  '/farmer/logistics': typeof FarmerLogisticsRoute
  '/farmer/lots': typeof FarmerLotsRouteWithChildren
  '/farmer/offers': typeof FarmerOffersRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/prices': typeof FarmerPricesRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/storage': typeof FarmerStorageRoute
  '/user-history/$userId': typeof UserHistoryUserIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/audit': typeof AuditIndexRoute
  '/auth': typeof AuthIndexRoute
  '/chatbot': typeof ChatbotIndexRoute
  '/coordinator': typeof CoordinatorIndexRoute
  '/farmer': typeof FarmerIndexRoute
  '/flags-reported': typeof FlagsReportedIndexRoute
  '/history': typeof HistoryIndexRoute
  '/home': typeof HomeIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/pae-expert': typeof PaeExpertIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/farmer/buyers/$buyerId': typeof FarmerBuyersBuyerIdRoute
  '/farmer/lots/$lotId': typeof FarmerLotsLotIdRoute
  '/farmer/lots/new': typeof FarmerLotsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/farmer': typeof FarmerRouteWithChildren
  '/whatsapp-history': typeof WhatsappHistoryRoute
  '/coordinator/profile': typeof CoordinatorProfileRoute
  '/farmer/buyers': typeof FarmerBuyersRouteWithChildren
  '/farmer/grievances': typeof FarmerGrievancesRoute
  '/farmer/logistics': typeof FarmerLogisticsRoute
  '/farmer/lots': typeof FarmerLotsRouteWithChildren
  '/farmer/offers': typeof FarmerOffersRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/prices': typeof FarmerPricesRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/storage': typeof FarmerStorageRoute
  '/user-history/$userId': typeof UserHistoryUserIdRoute
  '/user/$userId': typeof UserUserIdRoute
  '/audit/': typeof AuditIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/chatbot/': typeof ChatbotIndexRoute
  '/coordinator/': typeof CoordinatorIndexRoute
  '/farmer/': typeof FarmerIndexRoute
  '/flags-reported/': typeof FlagsReportedIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/home/': typeof HomeIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/pae-expert/': typeof PaeExpertIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/farmer/buyers/$buyerId': typeof FarmerBuyersBuyerIdRoute
  '/farmer/lots/$lotId': typeof FarmerLotsLotIdRoute
  '/farmer/lots/new': typeof FarmerLotsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/farmer'
    | '/whatsapp-history'
    | '/coordinator/profile'
    | '/farmer/buyers'
    | '/farmer/grievances'
    | '/farmer/logistics'
    | '/farmer/lots'
    | '/farmer/offers'
    | '/farmer/payments'
    | '/farmer/prices'
    | '/farmer/profile'
    | '/farmer/storage'
    | '/user-history/$userId'
    | '/user/$userId'
    | '/audit'
    | '/auth'
    | '/chatbot'
    | '/coordinator'
    | '/farmer/'
    | '/flags-reported'
    | '/history'
    | '/home'
    | '/notifications'
    | '/pae-expert'
    | '/profile'
    | '/farmer/buyers/$buyerId'
    | '/farmer/lots/$lotId'
    | '/farmer/lots/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/whatsapp-history'
    | '/coordinator/profile'
    | '/farmer/buyers'
    | '/farmer/grievances'
    | '/farmer/logistics'
    | '/farmer/lots'
    | '/farmer/offers'
    | '/farmer/payments'
    | '/farmer/prices'
    | '/farmer/profile'
    | '/farmer/storage'
    | '/user-history/$userId'
    | '/user/$userId'
    | '/audit'
    | '/auth'
    | '/chatbot'
    | '/coordinator'
    | '/farmer'
    | '/flags-reported'
    | '/history'
    | '/home'
    | '/notifications'
    | '/pae-expert'
    | '/profile'
    | '/farmer/buyers/$buyerId'
    | '/farmer/lots/$lotId'
    | '/farmer/lots/new'
  id:
    | '__root__'
    | '/'
    | '/farmer'
    | '/whatsapp-history'
    | '/coordinator/profile'
    | '/farmer/buyers'
    | '/farmer/grievances'
    | '/farmer/logistics'
    | '/farmer/lots'
    | '/farmer/offers'
    | '/farmer/payments'
    | '/farmer/prices'
    | '/farmer/profile'
    | '/farmer/storage'
    | '/user-history/$userId'
    | '/user/$userId'
    | '/audit/'
    | '/auth/'
    | '/chatbot/'
    | '/coordinator/'
    | '/farmer/'
    | '/flags-reported/'
    | '/history/'
    | '/home/'
    | '/notifications/'
    | '/pae-expert/'
    | '/profile/'
    | '/farmer/buyers/$buyerId'
    | '/farmer/lots/$lotId'
    | '/farmer/lots/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarmerRoute: typeof FarmerRouteWithChildren
  WhatsappHistoryRoute: typeof WhatsappHistoryRoute
  CoordinatorProfileRoute: typeof CoordinatorProfileRoute
  UserHistoryUserIdRoute: typeof UserHistoryUserIdRoute
  UserUserIdRoute: typeof UserUserIdRoute
  AuditIndexRoute: typeof AuditIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ChatbotIndexRoute: typeof ChatbotIndexRoute
  CoordinatorIndexRoute: typeof CoordinatorIndexRoute
  FlagsReportedIndexRoute: typeof FlagsReportedIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  PaeExpertIndexRoute: typeof PaeExpertIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-history': {
      id: '/whatsapp-history'
      path: '/whatsapp-history'
      fullPath: '/whatsapp-history'
      preLoaderRoute: typeof WhatsappHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer': {
      id: '/farmer'
      path: '/farmer'
      fullPath: '/farmer'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pae-expert/': {
      id: '/pae-expert/'
      path: '/pae-expert'
      fullPath: '/pae-expert'
      preLoaderRoute: typeof PaeExpertIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags-reported/': {
      id: '/flags-reported/'
      path: '/flags-reported'
      fullPath: '/flags-reported'
      preLoaderRoute: typeof FlagsReportedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/': {
      id: '/farmer/'
      path: '/'
      fullPath: '/farmer/'
      preLoaderRoute: typeof FarmerIndexRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/coordinator/': {
      id: '/coordinator/'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof CoordinatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot/': {
      id: '/chatbot/'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$userId': {
      id: '/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof UserUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-history/$userId': {
      id: '/user-history/$userId'
      path: '/user-history/$userId'
      fullPath: '/user-history/$userId'
      preLoaderRoute: typeof UserHistoryUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/storage': {
      id: '/farmer/storage'
      path: '/storage'
      fullPath: '/farmer/storage'
      preLoaderRoute: typeof FarmerStorageRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/profile': {
      id: '/farmer/profile'
      path: '/profile'
      fullPath: '/farmer/profile'
      preLoaderRoute: typeof FarmerProfileRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/prices': {
      id: '/farmer/prices'
      path: '/prices'
      fullPath: '/farmer/prices'
      preLoaderRoute: typeof FarmerPricesRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/payments': {
      id: '/farmer/payments'
      path: '/payments'
      fullPath: '/farmer/payments'
      preLoaderRoute: typeof FarmerPaymentsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/offers': {
      id: '/farmer/offers'
      path: '/offers'
      fullPath: '/farmer/offers'
      preLoaderRoute: typeof FarmerOffersRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/lots': {
      id: '/farmer/lots'
      path: '/lots'
      fullPath: '/farmer/lots'
      preLoaderRoute: typeof FarmerLotsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/logistics': {
      id: '/farmer/logistics'
      path: '/logistics'
      fullPath: '/farmer/logistics'
      preLoaderRoute: typeof FarmerLogisticsRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/grievances': {
      id: '/farmer/grievances'
      path: '/grievances'
      fullPath: '/farmer/grievances'
      preLoaderRoute: typeof FarmerGrievancesRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/farmer/buyers': {
      id: '/farmer/buyers'
      path: '/buyers'
      fullPath: '/farmer/buyers'
      preLoaderRoute: typeof FarmerBuyersRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/coordinator/profile': {
      id: '/coordinator/profile'
      path: '/coordinator/profile'
      fullPath: '/coordinator/profile'
      preLoaderRoute: typeof CoordinatorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/lots/new': {
      id: '/farmer/lots/new'
      path: '/new'
      fullPath: '/farmer/lots/new'
      preLoaderRoute: typeof FarmerLotsNewRouteImport
      parentRoute: typeof FarmerLotsRoute
    }
    '/farmer/lots/$lotId': {
      id: '/farmer/lots/$lotId'
      path: '/$lotId'
      fullPath: '/farmer/lots/$lotId'
      preLoaderRoute: typeof FarmerLotsLotIdRouteImport
      parentRoute: typeof FarmerLotsRoute
    }
    '/farmer/buyers/$buyerId': {
      id: '/farmer/buyers/$buyerId'
      path: '/$buyerId'
      fullPath: '/farmer/buyers/$buyerId'
      preLoaderRoute: typeof FarmerBuyersBuyerIdRouteImport
      parentRoute: typeof FarmerBuyersRoute
    }
  }
}

interface FarmerBuyersRouteChildren {
  FarmerBuyersBuyerIdRoute: typeof FarmerBuyersBuyerIdRoute
}

const FarmerBuyersRouteChildren: FarmerBuyersRouteChildren = {
  FarmerBuyersBuyerIdRoute: FarmerBuyersBuyerIdRoute,
}

const FarmerBuyersRouteWithChildren = FarmerBuyersRoute._addFileChildren(
  FarmerBuyersRouteChildren,
)

interface FarmerLotsRouteChildren {
  FarmerLotsLotIdRoute: typeof FarmerLotsLotIdRoute
  FarmerLotsNewRoute: typeof FarmerLotsNewRoute
}

const FarmerLotsRouteChildren: FarmerLotsRouteChildren = {
  FarmerLotsLotIdRoute: FarmerLotsLotIdRoute,
  FarmerLotsNewRoute: FarmerLotsNewRoute,
}

const FarmerLotsRouteWithChildren = FarmerLotsRoute._addFileChildren(
  FarmerLotsRouteChildren,
)

interface FarmerRouteChildren {
  FarmerBuyersRoute: typeof FarmerBuyersRouteWithChildren
  FarmerGrievancesRoute: typeof FarmerGrievancesRoute
  FarmerLogisticsRoute: typeof FarmerLogisticsRoute
  FarmerLotsRoute: typeof FarmerLotsRouteWithChildren
  FarmerOffersRoute: typeof FarmerOffersRoute
  FarmerPaymentsRoute: typeof FarmerPaymentsRoute
  FarmerPricesRoute: typeof FarmerPricesRoute
  FarmerProfileRoute: typeof FarmerProfileRoute
  FarmerStorageRoute: typeof FarmerStorageRoute
  FarmerIndexRoute: typeof FarmerIndexRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerBuyersRoute: FarmerBuyersRouteWithChildren,
  FarmerGrievancesRoute: FarmerGrievancesRoute,
  FarmerLogisticsRoute: FarmerLogisticsRoute,
  FarmerLotsRoute: FarmerLotsRouteWithChildren,
  FarmerOffersRoute: FarmerOffersRoute,
  FarmerPaymentsRoute: FarmerPaymentsRoute,
  FarmerPricesRoute: FarmerPricesRoute,
  FarmerProfileRoute: FarmerProfileRoute,
  FarmerStorageRoute: FarmerStorageRoute,
  FarmerIndexRoute: FarmerIndexRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarmerRoute: FarmerRouteWithChildren,
  WhatsappHistoryRoute: WhatsappHistoryRoute,
  CoordinatorProfileRoute: CoordinatorProfileRoute,
  UserHistoryUserIdRoute: UserHistoryUserIdRoute,
  UserUserIdRoute: UserUserIdRoute,
  AuditIndexRoute: AuditIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  ChatbotIndexRoute: ChatbotIndexRoute,
  CoordinatorIndexRoute: CoordinatorIndexRoute,
  FlagsReportedIndexRoute: FlagsReportedIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  PaeExpertIndexRoute: PaeExpertIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
